### ISSUE TITLE
Implementing the integrity_hash

### ISSUE THREAD

**Issue by aaademosu** [iamraphson/angularjs-ravepayment#2]
@iamraphson 

Kindly check the commit below and if ok by you, i can create a pull request to merge. The update includes the integrity_hash attribute as suggested in the README.

https://github.com/aaademosu/angularjs-ravepayment/commit/efd4bcc54adaf9f8069cedb2254f8d9e85916102

**Comment by iamraphson** [comment]
@temiadesina what did you think about the `integrity_hash` attribute?

**Comment by temiadesina** [comment]
Hi @iamraphson yes please do add it, the merchant would compute the hash on their server and use that to pass it to the getpaidsetup function.

**Comment by iamraphson** [comment]
Thanks @temiadesina .. @aaademosu your PR is welcome. you can send it
